name: 🔧 Enhancement Request
description: Request/Suggest any enhancement in features of a project you think is missing
title: "Title: "
labels: "Enhancement Request"
body:
  - type: textarea #extension
    attributes:
      label: Which pre-existing JavaScript project will you be working on?
      description: Mention the extension and what it does.
      placeholder: Type here.
    validations:
      required: true

  - type: textarea #enhancement
    attributes:
      label: Describe your enhancement/improvement
      description: A clear and concise description of what feature you will be adding to the extension and/or the type of enhancement. Make sure your work is significant. 
      placeholder: Kindly elaborate.
    validations:
      required: true
      
  - type: textarea #NoteToReviewers
    attributes:
      label: Anything you need to say to the Reviewers
      description: For the Reviewers.
      placeholder: Type here.
      
  - type: textarea #Additional Context
    attributes:
      label: Add any other context or screenshots about the enhancement here.
      description: Any miscellaneous suggestions you'd like to give.
